# Generated by Django 5.0.6 on 2024-12-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0003_wishlist_wishlistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
