# Generated by Django 5.0.6 on 2024-12-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0004_product_sold_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
