# Generated by Django 5.0.6 on 2024-12-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0006_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to="retail/categories/icons/"
            ),
        ),
    ]
