# Generated by Django 5.1.4 on 2025-01-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='country',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_floor',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='email_address',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
