# Generated by Django 5.1.4 on 2025-01-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0009_rename_country_address_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Card', 'Card'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=50),
        ),
    ]
